In [1]:
# Instalar numpy
!pip install numpy

In [2]:
# Numpy es una librería utilizada para hacer operaciones
# de manera rápida y fácil con arreglos y matrices.

# Tomado de : https://numpy.org/doc/stable/user/quickstart.html

# Tenemos que importar la librería a nuestro cuaderno.
import numpy as np

In [3]:
# Creamos una lista únicamente con números.

x = [1, 5.5, 20, 2, 9]

print(x)
print(f"Tercer elemento: {x[2]}")
print(type(x))

[1, 5.5, 20, 2, 9]
Tercer elemento: 20
<class 'list'>


In [4]:
# Convertimos a un arreglo de numpy.
# Los arreglos son vectores matemáticos.
# Se accede a los elementos individuales 
# de la misma manera que en una lista.

y = np.array(x)

print(x)
print(f"Tercer elemento: {y[2]}")
print(type(y))

[1, 5.5, 20, 2, 9]
Tercer elemento: 20.0
<class 'numpy.ndarray'>


In [5]:
# El arreglo que creamos, es un objeto con métodos, o funciones
# inherentes al propio objeto.

# Suma
print( y.sum() )

# Promedio
print( y.mean() )

# Desviación estándar
print( y.std() )

# Varianza
print( y.var() )

# Mínimo
print( y.min() )

# Máximo
print( y.max() )

# Suma acumulada
print( y.cumsum() )

37.5
7.5
6.855654600401044
47.0
1.0
20.0
[ 1.   6.5 26.5 28.5 37.5]


In [6]:
# Podemos ordenar los valores.

print( y )

print( np.sort(y) )

[ 1.   5.5 20.   2.   9. ]
[ 1.   2.   5.5  9.  20. ]


In [7]:
# Linspace() crea un arreglo con un valor inicial,
# final, y una cierta cantidad de elementos igualmente
# espaciados entre ellos.

a = np.linspace( 0, 10, 11 )
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [8]:
a = np.linspace( 0, 10, 10 )
print(a)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [9]:
# arange() tiene un valor inicial, uno final, y un
# incremento entre elementos.
# El elemento final no se incluye.

a = np.arange(1, 10, 1)
print(a)

[1 2 3 4 5 6 7 8 9]


In [10]:
a = np.arange(1, 10, 4)
print(a)

[1 5 9]


In [11]:
# zeros() crea un arreglo vacío de cierta longitud.

a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [12]:
# shape nos permite ver las dimensiones del arreglo.
print( a.shape )

(5,)


In [13]:
# Podemos declarar una matriz con una serie de listas.

a = np.array( [ [1, 2, 3], 
                [4, 5, 6],
                [7, 8, 9] ] )

print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [14]:
# Podemos declarar una matriz con una serie de listas.

a = np.array( [ [1, 2], 
                [4, 5],
                [7, 8] ] )

print(a)
print(a.shape)

[[1 2]
 [4 5]
 [7 8]]
(3, 2)


In [15]:
# Para acceder a los elementos, se determinan los índices de cada eje.

print( a[0, 1] )

2


In [16]:
# Se pueden utlilizar los dobles puntos.

print( a[0:2, 0] )

[1 4]


In [17]:
print( a[:, 0] )

[1 4 7]


In [18]:
print( a[0, :] )

[1 2]


In [19]:
# ones() crea un arreglo de puros unos.
# se puede especificar las dimensiones de la matriz.
# lo mismo aplica para zeros()

a = np.ones( [5, 3] )
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
# Matriz aleatoria.

a = np.random.randn( 6, 4 )
print(a)

[[ 1.35338725  0.21384131  0.46931214 -0.83915028]
 [ 0.16222295  0.06047925  0.92413855 -1.53412881]
 [ 0.02045796  1.11679333 -1.27043484  0.96955933]
 [ 0.21923787  0.73236241 -0.84472689  0.95288318]
 [-0.97059823  1.46979254  0.04775345  0.09049409]
 [-0.18481799 -0.46675625 -1.06915847 -0.54595652]]


In [21]:
# Los métodos se aplican para toda la matriz o para un solo eje.

print( a.sum() )
print( a.sum(axis = 0) ) # axis = 0, filas, sumar verticalmente
print( a.sum(axis = 1) ) # axis = 1, columnas, sumar horizontalmente

1.0769873177532232
[ 0.59988981  3.12651258 -1.74311607 -0.90629901]
[ 1.19739042 -0.38728806  0.83637577  1.05975657  0.63744186 -2.26668924]


In [22]:
# Se pueden realizar operaciones matriciales.

a = np.array( [ [1, 2, 3], 
                [4, 5, 6],
                [7, 8, 9] ] )

b = np.array( [ [1, 7, 2], 
                [3, 9, 4],
                [5, 0, 6] ] )

# Traza
print(a.trace())

# Traspuesta
print(a.T)

# Multiplicación elemento por elemento
print( a * b )

# Multiplicación matricial
print( a @ b )

# Matriz inversa.

print(np.linalg.inv(b))


15
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 1 14  6]
 [12 45 24]
 [35  0 54]]
[[ 22  25  28]
 [ 49  73  64]
 [ 76 121 100]]
[[-2.45454545  1.90909091 -0.45454545]
 [-0.09090909  0.18181818 -0.09090909]
 [ 2.04545455 -1.59090909  0.54545455]]


In [23]:
# Operaciones matemáticas elemento por elemento.

# Matriz original.
print( a )
print()

# Operaciones básicas.
print(a * 2)
print()

# Exponencial.
print( np.exp(a) )
print()

# Raíz cuadrada.
print( np.sqrt(a) )
print()

# seno y coseno.
print( np.sin(a) )
print( np.cos(a) )
print()

# Logaritmo natural
print( np.log(a) )
print()

# También es posible aplicarlas a un solo número.
print( np.cos(np.radians(30)) )

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]

0.8660254037844387


In [24]:
# "Aplanar" matriz

print(a)
print()

print(a.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3 4 5 6 7 8 9]


In [25]:
# Números especiales.

print(np.pi)
print(np.nan)
print(np.e)

3.141592653589793
nan
2.718281828459045


In [26]:
# Explicar cómo obtener documentación, y stackoverflow.

In [27]:
# Busca la serie 1 de la materia de álgebra de la DCB.
# Resuelve los ejercicios 1, 2, 3.
# Busca la serie 6 de la materia de álgebra de la DCB.
# Resuelve los ejercicios 2, 4, 10, 12.