In [1]:
# Numpy es una librería utilizada para hacer operaciones
# de manera rápida y fácil con arreglos y matrices.

# Tenemos que importar la librería a nuestro cuaderno.
import numpy as np

In [2]:
# Creamos una lista únicamente con números.

x = [1, 2, 5.5, 9, 20]

print(x)
print(f"Tercer elemento: {x[2]}")
print(type(x))

[1, 2, 5.5, 9, 20]
Tercer elemento: 5.5
<class 'list'>


In [3]:
# Convertimos a un arreglo de numpy.
# Los arreglos son vectores matemáticos.
# Se accede a los elementos individuales 
# de la misma manera que en una lista.

y = np.array(x)

print(x)
print(f"Tercer elemento: {y[2]}")
print(type(y))

[1, 2, 5.5, 9, 20]
Tercer elemento: 5.5
<class 'numpy.ndarray'>


In [4]:
# El arreglo que creamos, es un objeto con métodos, o funciones
# inherentes al propio objeto.

# Suma
print( y.sum() )

# Promedio
print( y.mean() )

# Desviación estándar
print( y.std() )

# Varianza
print( y.var() )

# Mínimo
print( y.min() )

# Máximo
print( y.max() )

37.5
7.5
6.855654600401044
47.0
1.0
20.0


In [5]:
# Linspace() crea un arreglo con un valor inicial,
# final, y una cierta cantidad de elementos igualmente
# espaciados entre ellos.

a = np.linspace( 0, 10, 11 )
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [6]:
a = np.linspace( 0, 10, 10 )
print(a)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [7]:
# arange() tiene un valor inicial, uno final, y un
# incremento entre elementos.
# El elemento final no se incluye.

a = np.arange(1, 10, 1)
print(a)

[1 2 3 4 5 6 7 8 9]


In [8]:
a = np.arange(1, 10, 4)
print(a)

[1 5 9]


In [9]:
# zeros() crea un arreglo vacío de cierta longitud.

a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [10]:
# shape nos permite ver las dimensiones del arreglo.
print( a.shape )

(5,)


In [11]:
# Podemos declarar una matriz con una serie de listas.

a = np.array( [ [1, 2, 3], 
                [4, 5, 6],
                [7, 8, 9] ] )

print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [12]:
# Podemos declarar una matriz con una serie de listas.

a = np.array( [ [1, 2], 
                [4, 5],
                [7, 8] ] )

print(a)
print(a.shape)

[[1 2]
 [4 5]
 [7 8]]
(3, 2)


In [13]:
# Para acceder a los elementos, se determinan los índices de cada eje.

print( a[0, 1] )

2


In [14]:
# Se pueden utlilizar los dobles puntos.

print( a[0:2, 0] )

[1 4]


In [15]:
print( a[:, 0] )

[1 4 7]


In [16]:
# ones() crea un arreglo de puros unos.
# se puede especificar las dimensiones de la matriz.
# lo mismo aplica para zeros()

a = np.ones( (5, 3) )
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
# Los métodos se aplican para toda la matriz o para un solo eje.

print( a.sum() )
print( a.sum(axis = 0) )
print( a.sum(axis = 1) )

15.0
[5. 5. 5.]
[3. 3. 3. 3. 3.]


In [20]:
# Se pueden realizar operaciones matriciales.

a = np.array( [ [1, 2, 3], 
                [4, 5, 6],
                [7, 8, 9] ] )

b = np.array( [ [1, 7, 2], 
                [3, 9, 4],
                [5, 0, 6] ] )

# Traza
print(a.trace())

# Traspuesta
print(a.T)

# Multiplicación elemento por elemento
print( a * b )

# Multiplicación matricial
print( a @ b )

# Aplicar una operación a cada elemento.
print( a.apply( T ) )


15
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 1 14  6]
 [12 45 24]
 [35  0 54]]
[[ 22  25  28]
 [ 49  73  64]
 [ 76 121 100]]
