In [1]:
# Numpy es una librería utilizada para hacer operaciones
# de manera rápida y fácil con arreglos y matrices.

# Tomado de : https://numpy.org/doc/stable/user/quickstart.html

# Tenemos que importar la librería a nuestro cuaderno.
import numpy as np

In [42]:
# Creamos una lista únicamente con números.

x = [1, 5.5, 20, 2, 9]

print(x)
print(f"Tercer elemento: {x[2]}")
print(type(x))

[1, 5.5, 20, 2, 9]
Tercer elemento: 20
<class 'list'>


In [43]:
# Convertimos a un arreglo de numpy.
# Los arreglos son vectores matemáticos.
# Se accede a los elementos individuales 
# de la misma manera que en una lista.

y = np.array(x)

print(x)
print(f"Tercer elemento: {y[2]}")
print(type(y))

[1, 5.5, 20, 2, 9]
Tercer elemento: 20.0
<class 'numpy.ndarray'>


In [4]:
# El arreglo que creamos, es un objeto con métodos, o funciones
# inherentes al propio objeto.

# Suma
print( y.sum() )

# Promedio
print( y.mean() )

# Desviación estándar
print( y.std() )

# Varianza
print( y.var() )

# Mínimo
print( y.min() )

# Máximo
print( y.max() )

# Suma acumulada
print( y.cumsum() )

37.5
7.5
6.855654600401044
47.0
1.0
20.0
[ 1.   3.   8.5 17.5 37.5]


In [44]:
# Podemos ordenar los valores,

print( y )

print( np.sort(y) )

[ 1.   5.5 20.   2.   9. ]
[ 1.   2.   5.5  9.  20. ]


In [5]:
# Linspace() crea un arreglo con un valor inicial,
# final, y una cierta cantidad de elementos igualmente
# espaciados entre ellos.

a = np.linspace( 0, 10, 11 )
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [6]:
a = np.linspace( 0, 10, 10 )
print(a)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [7]:
# arange() tiene un valor inicial, uno final, y un
# incremento entre elementos.
# El elemento final no se incluye.

a = np.arange(1, 10, 1)
print(a)

[1 2 3 4 5 6 7 8 9]


In [8]:
a = np.arange(1, 10, 4)
print(a)

[1 5 9]


In [9]:
# zeros() crea un arreglo vacío de cierta longitud.

a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [10]:
# shape nos permite ver las dimensiones del arreglo.
print( a.shape )

(5,)


In [11]:
# Podemos declarar una matriz con una serie de listas.

a = np.array( [ [1, 2, 3], 
                [4, 5, 6],
                [7, 8, 9] ] )

print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [12]:
# Podemos declarar una matriz con una serie de listas.

a = np.array( [ [1, 2], 
                [4, 5],
                [7, 8] ] )

print(a)
print(a.shape)

[[1 2]
 [4 5]
 [7 8]]
(3, 2)


In [13]:
# Para acceder a los elementos, se determinan los índices de cada eje.

print( a[0, 1] )

2


In [14]:
# Se pueden utlilizar los dobles puntos.

print( a[0:2, 0] )

[1 4]


In [15]:
print( a[:, 0] )

[1 4 7]


In [16]:
# ones() crea un arreglo de puros unos.
# se puede especificar las dimensiones de la matriz.
# lo mismo aplica para zeros()

a = np.ones( (5, 3) )
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
# Matriz aleatoria.

a = np.random.randn(6, 4)
print(a)

[[-0.99331087 -0.39138792 -1.66630499 -0.61374436]
 [-1.43213993  0.7583674  -0.6520068   0.577616  ]
 [ 0.87177097  1.09183987 -0.20867032 -0.66932711]
 [ 0.69072731 -0.24080444 -0.05766735 -1.82648102]
 [ 1.87508927  0.79076952  1.93086986  0.12453224]
 [-0.03764674  0.3227872  -0.0589606   1.54222813]]


In [18]:
# Los métodos se aplican para toda la matriz o para un solo eje.

print( a.sum() )
print( a.sum(axis = 0) )
print( a.sum(axis = 1) )

1.7281453358690975
[ 0.97449001  2.33157163 -0.71274019 -0.86517612]
[-3.66474814 -0.74816332  1.08561342 -1.4342255   4.72126089  1.76840799]


In [28]:
# Se pueden realizar operaciones matriciales.

a = np.array( [ [1, 2, 3], 
                [4, 5, 6],
                [7, 8, 9] ] )

b = np.array( [ [1, 7, 2], 
                [3, 9, 4],
                [5, 0, 6] ] )

# Traza
print(a.trace())

# Traspuesta
print(a.T)

# Multiplicación elemento por elemento
print( a * b )

# Multiplicación matricial
print( a @ b )

# Matriz inversa.

print(np.linalg.inv(a))


15
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 1 14  6]
 [12 45 24]
 [35  0 54]]
[[ 22  25  28]
 [ 49  73  64]
 [ 76 121 100]]
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [29]:
# Operaciones matemáticas elemento por elemento.

# Matriz original.
print( a )
print()

# Operaciones básicas.
print(a * 2)
print()

# Exponencial.
print( np.exp(a) )
print()

# Raíz cuadrada.
print( np.sqrt(a) )
print()

# seno y coseno.
print( np.sin(a) )
print( np.cos(a) )
print()

# Logaritmo natural
print( np.log(a) )
print()

# También es posible aplicarlas a un solo número.
print( np.cos(np.radians(30)) )

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]

0.8660254037844387


In [21]:
# Si le asigno una variable a un subconjunto y lo modifico,
# el arreglo entero se modifica; esto es una vista.

print(a)
print()

a_1 = a[0:2, 0:2]
print(a_1)
print()

a_1[0,0] = 0
print(a_1)
print()

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2]
 [4 5]]

[[0 2]
 [4 5]]

[[0 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
# Para modificar solo el subconjunto, se hace una copia.

print(a)
print()

a_1 = a[0:2, 0:2].copy()
print(a_1)
print()

a_1[0,0] = -10
print(a_1)
print()

print(a)

[[0 2 3]
 [4 5 6]
 [7 8 9]]

[[0 2]
 [4 5]]

[[-10   2]
 [  4   5]]

[[0 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
# "Aplanar" matriz

print(a)
print()

print(a.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3 4 5 6 7 8 9]


In [32]:
# Números especiales.

print(np.pi)
print(np.nan)
print(np.e)

3.141592653589793
nan
2.718281828459045


In [23]:
# Explicar cómo obtener documentación, y stackoverflow.

In [24]:
# Busca la serie de la materia de álgebra.
# Resuelve los ejercicios 1, 2, 3.
# Busca la serie 6 de la materia de álgebra.
# Resuelve los ejercicios 2, 4, 10, 12.