In [76]:
!pip install pandas

In [77]:
# Pandas es el Excel de python.
# Obtenido de: https://pandas.pydata.org/docs/user_guide/10min.html

import pandas as pd
import numpy as np

In [78]:
# Una columna en pandas se llama una serie
# np.nan es un valor faltante
# Cada elemento tiene un índice.

s = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [79]:
# El índice puede ser una fecha

fechas = pd.date_range("20130101", periods = 6, freq = "D")

print(fechas)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')


In [80]:
s = pd.Series([1, 3, 5, np.nan, 6, 8], index = fechas, name = "datos")

print(s)

2013-01-01    1.0
2013-01-02    3.0
2013-01-03    5.0
2013-01-04    NaN
2013-01-05    6.0
2013-01-06    8.0
Freq: D, Name: datos, dtype: float64


In [81]:
# Un dataframe es un conjunto de columnas.

# creado a partir de arreglos de numpy.
df = pd.DataFrame( np.random.randn(6, 4), index = fechas,
    columns = ["A", "B", "C", "D"] )

print(df)

                   A         B         C         D
2013-01-01  0.405006  0.748404  0.244871 -1.181110
2013-01-02 -1.817821 -0.288873 -0.719807  0.170888
2013-01-03  1.075171 -0.969841 -0.120263  1.199907
2013-01-04  0.393199 -0.174549 -0.809589  1.432332
2013-01-05  0.210182  0.855749 -0.382265  0.634273
2013-01-06 -1.629181  0.510364  1.159254  0.563412


In [82]:
# head() y tail() muestran la parte 
# superior e inferior del Dataframe.

print(df.head())
print()
print(df.tail())

                   A         B         C         D
2013-01-01  0.405006  0.748404  0.244871 -1.181110
2013-01-02 -1.817821 -0.288873 -0.719807  0.170888
2013-01-03  1.075171 -0.969841 -0.120263  1.199907
2013-01-04  0.393199 -0.174549 -0.809589  1.432332
2013-01-05  0.210182  0.855749 -0.382265  0.634273

                   A         B         C         D
2013-01-02 -1.817821 -0.288873 -0.719807  0.170888
2013-01-03  1.075171 -0.969841 -0.120263  1.199907
2013-01-04  0.393199 -0.174549 -0.809589  1.432332
2013-01-05  0.210182  0.855749 -0.382265  0.634273
2013-01-06 -1.629181  0.510364  1.159254  0.563412


In [83]:
# Podemos acceder al índice y las columnas.

print(df.index)
print()
print(df.columns)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

Index(['A', 'B', 'C', 'D'], dtype='object')


In [84]:
# Trasponer.

print(df.T)

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    0.405006   -1.817821    1.075171    0.393199    0.210182   -1.629181
B    0.748404   -0.288873   -0.969841   -0.174549    0.855749    0.510364
C    0.244871   -0.719807   -0.120263   -0.809589   -0.382265    1.159254
D   -1.181110    0.170888    1.199907    1.432332    0.634273    0.563412


In [85]:
# Convertir a un arreglo de numpy.

print( df.to_numpy() )

[[ 0.40500581  0.748404    0.24487114 -1.18111028]
 [-1.81782124 -0.28887308 -0.71980652  0.17088785]
 [ 1.0751714  -0.9698415  -0.12026286  1.19990699]
 [ 0.39319856 -0.17454856 -0.80958924  1.43233223]
 [ 0.21018161  0.85574876 -0.38226455  0.63427349]
 [-1.62918135  0.51036378  1.15925417  0.56341246]]


In [86]:
# Estadística descriptiva.

print( df.describe() )

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.227241  0.113542 -0.104633  0.469950
std    1.197304  0.711343  0.731066  0.928460
min   -1.817821 -0.969841 -0.809589 -1.181110
25%   -1.169341 -0.260292 -0.635421  0.269019
50%    0.301690  0.167908 -0.251264  0.598843
75%    0.402054  0.688894  0.153588  1.058499
max    1.075171  0.855749  1.159254  1.432332


In [87]:
# Ordenar datos.

# Por índice.

print( df.sort_index(ascending = False) )

                   A         B         C         D
2013-01-06 -1.629181  0.510364  1.159254  0.563412
2013-01-05  0.210182  0.855749 -0.382265  0.634273
2013-01-04  0.393199 -0.174549 -0.809589  1.432332
2013-01-03  1.075171 -0.969841 -0.120263  1.199907
2013-01-02 -1.817821 -0.288873 -0.719807  0.170888
2013-01-01  0.405006  0.748404  0.244871 -1.181110


In [88]:
# Por columna.
print( df.sort_values(by = "B") )

                   A         B         C         D
2013-01-03  1.075171 -0.969841 -0.120263  1.199907
2013-01-02 -1.817821 -0.288873 -0.719807  0.170888
2013-01-04  0.393199 -0.174549 -0.809589  1.432332
2013-01-06 -1.629181  0.510364  1.159254  0.563412
2013-01-01  0.405006  0.748404  0.244871 -1.181110
2013-01-05  0.210182  0.855749 -0.382265  0.634273


In [89]:
# Escoger una columna.

print( df["A"] )

2013-01-01    0.405006
2013-01-02   -1.817821
2013-01-03    1.075171
2013-01-04    0.393199
2013-01-05    0.210182
2013-01-06   -1.629181
Freq: D, Name: A, dtype: float64


In [90]:
# Escoger una fila.

print(df.index[0])
print( df.loc[df.index[0]] )

2013-01-01 00:00:00
A    0.405006
B    0.748404
C    0.244871
D   -1.181110
Name: 2013-01-01 00:00:00, dtype: float64


In [91]:
# Escoger por número de fila.

print( df.iloc[0] )

A    0.405006
B    0.748404
C    0.244871
D   -1.181110
Name: 2013-01-01 00:00:00, dtype: float64


In [92]:
# Escoger por fila y columna.

print( df.loc[df.index[2], "B"] )

-0.9698414969728085


In [93]:
# Escoger por número de fila y columna.

print( df.iloc[2, 1] )

-0.9698414969728085


In [94]:
# Escoger una subsección del dataframe.

df_2 = df.iloc[2:4, 1:3]
print( df_2 )

                   B         C
2013-01-03 -0.969841 -0.120263
2013-01-04 -0.174549 -0.809589


In [95]:
df_2 = df.iloc[2:4, :]
print( df_2 )

# Las copias y vistas funcionan igual que en numpy!!

                   A         B         C         D
2013-01-03  1.075171 -0.969841 -0.120263  1.199907
2013-01-04  0.393199 -0.174549 -0.809589  1.432332


In [96]:
# Búsqueda por condiciones.

# En una columna.
print( df[df["A"] > 0] )

                   A         B         C         D
2013-01-01  0.405006  0.748404  0.244871 -1.181110
2013-01-03  1.075171 -0.969841 -0.120263  1.199907
2013-01-04  0.393199 -0.174549 -0.809589  1.432332
2013-01-05  0.210182  0.855749 -0.382265  0.634273


In [97]:
# En todo el dataframe.

print( df[df>0] )

                   A         B         C         D
2013-01-01  0.405006  0.748404  0.244871       NaN
2013-01-02       NaN       NaN       NaN  0.170888
2013-01-03  1.075171       NaN       NaN  1.199907
2013-01-04  0.393199       NaN       NaN  1.432332
2013-01-05  0.210182  0.855749       NaN  0.634273
2013-01-06       NaN  0.510364  1.159254  0.563412


In [98]:
# Agregar columnas.
# Todos los elementos de una columna son del mismo tipo.
# Las columnas pueden tener distintos tipos.

df["E"] = ["uno", "uno", "dos", "tres", "cuatro", "tres"]

print(df)

                   A         B         C         D       E
2013-01-01  0.405006  0.748404  0.244871 -1.181110     uno
2013-01-02 -1.817821 -0.288873 -0.719807  0.170888     uno
2013-01-03  1.075171 -0.969841 -0.120263  1.199907     dos
2013-01-04  0.393199 -0.174549 -0.809589  1.432332    tres
2013-01-05  0.210182  0.855749 -0.382265  0.634273  cuatro
2013-01-06 -1.629181  0.510364  1.159254  0.563412    tres


In [99]:
# Buscar un valor específico dentro de una columna.

df[ df["E"] == "uno" ]

A         B         C         D    E
2013-01-01  0.405006  0.748404  0.244871 -1.181110  uno
2013-01-02 -1.817821 -0.288873 -0.719807  0.170888  uno

In [100]:
# Nueva columna con arreglos.

df["F"] = np.linspace(1, 5, 6)
print(df.head())

                   A         B         C         D       E    F
2013-01-01  0.405006  0.748404  0.244871 -1.181110     uno  1.0
2013-01-02 -1.817821 -0.288873 -0.719807  0.170888     uno  1.8
2013-01-03  1.075171 -0.969841 -0.120263  1.199907     dos  2.6
2013-01-04  0.393199 -0.174549 -0.809589  1.432332    tres  3.4
2013-01-05  0.210182  0.855749 -0.382265  0.634273  cuatro  4.2


In [101]:
# Buscar valores específicos con isin()

print( df[ df["E"].isin( ["dos", "cuatro"] ) ] )

                   A         B         C         D       E    F
2013-01-03  1.075171 -0.969841 -0.120263  1.199907     dos  2.6
2013-01-05  0.210182  0.855749 -0.382265  0.634273  cuatro  4.2


In [102]:
df[ df["F"].isin( [1, 5] ) ]

A         B         C         D     E    F
2013-01-01  0.405006  0.748404  0.244871 -1.181110   uno  1.0
2013-01-06 -1.629181  0.510364  1.159254  0.563412  tres  5.0

In [103]:
# Podemos cambiar un valor específico.

df.iloc[0, 1] = 10
print(df)

                   A          B         C         D       E    F
2013-01-01  0.405006  10.000000  0.244871 -1.181110     uno  1.0
2013-01-02 -1.817821  -0.288873 -0.719807  0.170888     uno  1.8
2013-01-03  1.075171  -0.969841 -0.120263  1.199907     dos  2.6
2013-01-04  0.393199  -0.174549 -0.809589  1.432332    tres  3.4
2013-01-05  0.210182   0.855749 -0.382265  0.634273  cuatro  4.2
2013-01-06 -1.629181   0.510364  1.159254  0.563412    tres  5.0


In [104]:
# Quitar columna.

df = df.drop("E", axis = 1)
print(df)

                   A          B         C         D    F
2013-01-01  0.405006  10.000000  0.244871 -1.181110  1.0
2013-01-02 -1.817821  -0.288873 -0.719807  0.170888  1.8
2013-01-03  1.075171  -0.969841 -0.120263  1.199907  2.6
2013-01-04  0.393199  -0.174549 -0.809589  1.432332  3.4
2013-01-05  0.210182   0.855749 -0.382265  0.634273  4.2
2013-01-06 -1.629181   0.510364  1.159254  0.563412  5.0


In [105]:
# Quitar filas
df = df.drop(df.index[3], axis = 0)

df

A          B         C         D    F
2013-01-01  0.405006  10.000000  0.244871 -1.181110  1.0
2013-01-02 -1.817821  -0.288873 -0.719807  0.170888  1.8
2013-01-03  1.075171  -0.969841 -0.120263  1.199907  2.6
2013-01-05  0.210182   0.855749 -0.382265  0.634273  4.2
2013-01-06 -1.629181   0.510364  1.159254  0.563412  5.0

In [106]:
# Establecer valores con condicional.

df[df<0] = 0
print(df)

                   A          B         C         D    F
2013-01-01  0.405006  10.000000  0.244871  0.000000  1.0
2013-01-02  0.000000   0.000000  0.000000  0.170888  1.8
2013-01-03  1.075171   0.000000  0.000000  1.199907  2.6
2013-01-05  0.210182   0.855749  0.000000  0.634273  4.2
2013-01-06  0.000000   0.510364  1.159254  0.563412  5.0


In [107]:
# Agregamos algunos valores nulos.

df[df>2] = np.nan
print(df)

                   A         B         C         D    F
2013-01-01  0.405006       NaN  0.244871  0.000000  1.0
2013-01-02  0.000000  0.000000  0.000000  0.170888  1.8
2013-01-03  1.075171  0.000000  0.000000  1.199907  NaN
2013-01-05  0.210182  0.855749  0.000000  0.634273  NaN
2013-01-06  0.000000  0.510364  1.159254  0.563412  NaN


In [108]:
# Quitar filas con valores nulos.
print(df.dropna())
print()

# Rellenar valores nulos.
print(df.fillna(-100))
print()

# Determinar valores nulos.
print(df.isna())

              A    B    C         D    F
2013-01-02  0.0  0.0  0.0  0.170888  1.8

                   A           B         C         D      F
2013-01-01  0.405006 -100.000000  0.244871  0.000000    1.0
2013-01-02  0.000000    0.000000  0.000000  0.170888    1.8
2013-01-03  1.075171    0.000000  0.000000  1.199907 -100.0
2013-01-05  0.210182    0.855749  0.000000  0.634273 -100.0
2013-01-06  0.000000    0.510364  1.159254  0.563412 -100.0

                A      B      C      D      F
2013-01-01  False   True  False  False  False
2013-01-02  False  False  False  False  False
2013-01-03  False  False  False  False   True
2013-01-05  False  False  False  False   True
2013-01-06  False  False  False  False   True


In [109]:
# operaciones.

# Entre columnas.
df["G"] = df["A"] + df["C"]

print(df)
print()

# promedio
print(df.mean())
print()
print(df.mean(1))

                   A         B         C         D    F         G
2013-01-01  0.405006       NaN  0.244871  0.000000  1.0  0.649877
2013-01-02  0.000000  0.000000  0.000000  0.170888  1.8  0.000000
2013-01-03  1.075171  0.000000  0.000000  1.199907  NaN  1.075171
2013-01-05  0.210182  0.855749  0.000000  0.634273  NaN  0.210182
2013-01-06  0.000000  0.510364  1.159254  0.563412  NaN  1.159254

A    0.338072
B    0.341528
C    0.280825
D    0.513696
F    1.400000
G    0.618897
dtype: float64

2013-01-01    0.459951
2013-01-02    0.328481
2013-01-03    0.670050
2013-01-05    0.382077
2013-01-06    0.678457
dtype: float64


In [110]:
# Aplicar operación.
# np.cumsum() hace una suma acumulada.
df.apply(np.cumsum)

A         B         C         D    F         G
2013-01-01  0.405006       NaN  0.244871  0.000000  1.0  0.649877
2013-01-02  0.405006  0.000000  0.244871  0.170888  2.8  0.649877
2013-01-03  1.480177  0.000000  0.244871  1.370795  NaN  1.725048
2013-01-05  1.690359  0.855749  0.244871  2.005068  NaN  1.935230
2013-01-06  1.690359  1.366113  1.404125  2.568481  NaN  3.094484

In [111]:
# Logaritmo a cada elemento.
df["H"] = np.log( df["C"] )

df

/opt/homebrew/Caskroom/miniforge/base/envs/gv/lib/python3.9/site-packages/pandas/core/arraylike.py:364: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


A         B         C         D    F         G         H
2013-01-01  0.405006       NaN  0.244871  0.000000  1.0  0.649877 -1.407023
2013-01-02  0.000000  0.000000  0.000000  0.170888  1.8  0.000000      -inf
2013-01-03  1.075171  0.000000  0.000000  1.199907  NaN  1.075171      -inf
2013-01-05  0.210182  0.855749  0.000000  0.634273  NaN  0.210182      -inf
2013-01-06  0.000000  0.510364  1.159254  0.563412  NaN  1.159254  0.147777

In [112]:
# Recorrer una columna una cierta cantidad de filas.

df["I"] = df["C"].shift(2)

df

A         B         C         D    F         G         H  \
2013-01-01  0.405006       NaN  0.244871  0.000000  1.0  0.649877 -1.407023   
2013-01-02  0.000000  0.000000  0.000000  0.170888  1.8  0.000000      -inf   
2013-01-03  1.075171  0.000000  0.000000  1.199907  NaN  1.075171      -inf   
2013-01-05  0.210182  0.855749  0.000000  0.634273  NaN  0.210182      -inf   
2013-01-06  0.000000  0.510364  1.159254  0.563412  NaN  1.159254  0.147777   

                   I  
2013-01-01       NaN  
2013-01-02       NaN  
2013-01-03  0.244871  
2013-01-05  0.000000  
2013-01-06  0.000000

In [113]:
# Leer y escribir archivos es muy fácil con el formato
# csv, compatible con Excel.

# Escribir.
df.to_csv("Archivo1.csv")

In [114]:
# Leer archivo.

df_2 = pd.read_csv("Archivo1.csv", index_col = 0)
df_2

A         B         C         D    F         G         H  \
2013-01-01  0.405006       NaN  0.244871  0.000000  1.0  0.649877 -1.407023   
2013-01-02  0.000000  0.000000  0.000000  0.170888  1.8  0.000000      -inf   
2013-01-03  1.075171  0.000000  0.000000  1.199907  NaN  1.075171      -inf   
2013-01-05  0.210182  0.855749  0.000000  0.634273  NaN  0.210182      -inf   
2013-01-06  0.000000  0.510364  1.159254  0.563412  NaN  1.159254  0.147777   

                   I  
2013-01-01       NaN  
2013-01-02       NaN  
2013-01-03  0.244871  
2013-01-05  0.000000  
2013-01-06  0.000000

In [115]:
# El índice de fechas no se carga con el formato correcto.
print( df.index )
print( df_2.index )

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-05',
               '2013-01-06'],
              dtype='datetime64[ns]', freq=None)
Index(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-05', '2013-01-06'], dtype='object')


In [116]:
# Cambiamos al formato correcto.
df_2.index = pd.to_datetime( df_2.index )
df_2.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-05',
               '2013-01-06'],
              dtype='datetime64[ns]', freq=None)

In [117]:
# Correlación.

# Creamos un dataframe aleatorio.
df = pd.DataFrame( np.random.rand(100000, 2), columns = ["Col_1", "Col_2"] )

print( df.head() )
print()

# Matriz de correlación
print( df.corr() )
print()

# Matriz de covarianca
print( df.cov() )
print()

# Autocorrelación.
print( df["Col_1"].autocorr(lag = 1) )

      Col_1     Col_2
0  0.983965  0.050127
1  0.906384  0.335550
2  0.214511  0.155169
3  0.813020  0.863430
4  0.578360  0.781036

        Col_1   Col_2
Col_1  1.0000  0.0015
Col_2  0.0015  1.0000

          Col_1     Col_2
Col_1  0.083342  0.000125
Col_2  0.000125  0.083669

0.00048464378817299474


In [118]:
# Cargar el archivo Electrico_residencial_2010_2017
# Selecciona las entradas correspondientes a Baja California.
# Ordena los datos de menor a mayor consumo en 2010.
# Selecciona los municipios con una cantidad de usuarios en 2012 menor a 100
# Encuentra el municipio con mayor consumo en tarifa DAC.
# Selecciona solo la tarifa DAC para todos los municipios.
# Encuentra la correlación entre el consumo de 2012 y 2013.

In [119]:
# Agrupar datos

fechas = pd.date_range("20130101", periods = 200, freq = "D")
df = pd.DataFrame( np.random.randn(200, 4), index = fechas,
    columns = ["A", "B", "C", "D"] )

print(df)

                   A         B         C         D
2013-01-01 -1.220750  0.246002  2.351986  1.061611
2013-01-02  0.524894 -3.345036  0.417855 -2.891213
2013-01-03  0.296039 -0.069509 -0.421897  0.075144
2013-01-04  1.511488 -0.166646 -0.804257 -0.354594
2013-01-05  0.493615 -0.981581 -0.937825  0.996464
...              ...       ...       ...       ...
2013-07-15 -0.441957 -0.810924 -0.812820 -0.117883
2013-07-16 -1.188517 -1.154910 -1.866865  0.138533
2013-07-17  0.224287 -1.151766  0.248978  1.057335
2013-07-18 -0.058570 -1.791684  0.316113 -0.348543
2013-07-19 -0.409744  0.106588  0.698179  0.482049

[200 rows x 4 columns]


In [120]:
# Agrupamos y realizamos una operación.
df.groupby(df.index.month).sum()

A         B         C         D
1  4.998462 -2.073669 -1.709344 -7.113343
2 -2.516486 -0.914856 -1.780524 -7.906893
3  7.583140 -1.448229  0.813348 -9.781932
4 -7.997626 -6.518806 -6.417857  2.297530
5  3.622846 -5.678564  1.675448  7.171013
6  7.019563 -6.851240  3.149841  0.174455
7  0.895927 -8.541925  0.602251  5.768909

In [121]:
df.groupby(df.index.day).mean()

A         B         C         D
1  -0.093427 -0.131032  0.063438  0.383449
2   0.294861 -0.624617  0.134520  0.200541
3   0.358974 -0.349309 -0.138700 -0.325600
4   0.103916 -0.376646  0.470079  0.023335
5  -0.270047 -0.579265  0.182484 -0.012482
6   0.368846  0.399904  0.385671  0.275822
7  -0.204460 -0.168760  0.043468 -0.600002
8   0.358642 -0.002165  0.279910  0.103521
9  -0.212364  0.015047 -0.544510 -0.225394
10  0.189201 -0.032667 -0.106008 -0.317678
11  0.306048 -0.366788 -0.349622  0.532606
12  0.249595  0.058923  0.181983 -0.062644
13  0.011435  0.207352 -0.204690 -0.016021
14 -0.947709 -0.559255 -0.415899  0.056416
15 -0.114355 -0.309637  0.542793 -0.545936
16  0.395579 -0.102002 -0.092447  0.574435
17  0.726755 -0.479078  0.198917  0.612413
18 -0.151341 -0.190689  0.177852  0.276131
19 -0.193917  0.484406  0.061770 -0.188981
20  0.607394  0.080312 -0.559746  0.209954
21  0.571666 -0.029932 -0.432655 -0.495454
22  0.587711  0.441719 -0.136169 -0.070106
23 -0.305052 -0.453862 -0.231918 -0.534799
24 -0.280640  0.436142 -0.261738 -0.626082
25 -0.126754 -0.165242 -0.250258  0.203873
26  0.296593 -1.110274 -0.133557 -0.041567
27 -0.554698 -0.079314 -0.544595 -0.181545
28  0.336983  0.220905  0.331812 -0.061734
29 -0.261888 -0.834757  0.328654 -0.382276
30 -0.413209 -0.770424 -0.167795 -0.606972
31  0.649498  0.566613  0.914923 -0.022259

In [122]:
# Concatenar dataframes.

# Creamos un dataframe aleatorio.
df_1 = pd.DataFrame(np.random.randn(100,2), columns = ["Col_1", "Col_2"])
df_2 = pd.DataFrame(np.random.randn(100,2), columns = ["Col_1", "Col_2"])

print(df_1.head())
print()
print(df_2.head())
print()

# Concatenamos.
df = pd.concat([df_1, df_2], axis = 0, ignore_index = True)

# Reiniciamos el índice.
df = df.reset_index(drop = True)

print(df)

      Col_1     Col_2
0 -1.508641 -0.236958
1 -0.345513  0.188296
2  0.429979 -1.299435
3  0.320174  0.916676
4 -0.789388 -2.052451

      Col_1     Col_2
0 -0.449652 -0.726443
1  0.713304  0.203263
2  0.366794 -0.434259
3 -0.412114  0.575549
4 -1.314400 -0.078902

        Col_1     Col_2
0   -1.508641 -0.236958
1   -0.345513  0.188296
2    0.429979 -1.299435
3    0.320174  0.916676
4   -0.789388 -2.052451
..        ...       ...
195  1.315424  1.205990
196 -0.082110 -0.289320
197 -0.217560 -1.108567
198  0.801418  1.762060
199  0.674087 -0.150390

[200 rows x 2 columns]


In [123]:
# Concatenar dataframes.

# Creamos un dataframe aleatorio.
df_1 = pd.DataFrame(np.random.randn(100,2), columns = ["Col_1", "Col_2"])
df_2 = pd.DataFrame(np.random.randn(100,2), columns = ["Col_3", "Col_4"])

print(df_1.head())
print()
print(df_2.head())
print()

# Concatenamos.
df = pd.concat([df_1, df_2], axis = 1)

print(df)

      Col_1     Col_2
0 -0.153558  0.498055
1 -0.227531 -0.940505
2  2.234391 -0.798033
3 -2.370212  1.235076
4  0.424379 -0.535412

      Col_3     Col_4
0  0.683027  0.174353
1 -0.079426  0.072674
2 -1.907828  1.083841
3  0.178687 -0.065395
4 -0.717261  0.246544

       Col_1     Col_2     Col_3     Col_4
0  -0.153558  0.498055  0.683027  0.174353
1  -0.227531 -0.940505 -0.079426  0.072674
2   2.234391 -0.798033 -1.907828  1.083841
3  -2.370212  1.235076  0.178687 -0.065395
4   0.424379 -0.535412 -0.717261  0.246544
..       ...       ...       ...       ...
95 -0.446058 -0.775728  0.551037 -0.443230
96  0.364020  0.578839 -0.407735  0.400240
97 -0.484211  0.475334  0.041963  1.107414
98 -1.450585  2.107550  0.708739 -0.812024
99  0.925974  1.034610 -2.748673 -1.144608

[100 rows x 4 columns]
