In [1]:
!pip install pandas

In [2]:
# Pandas es el Excel de python.
# Obtenido de: https://pandas.pydata.org/docs/user_guide/10min.html

import pandas as pd
import numpy as np

In [3]:
# Una columna en pandas se llama una serie
# np.nan es un valor faltante
# Cada elemento tiene un índice.

s = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [4]:
# El índice puede ser una fecha

fechas = pd.date_range("20130101", periods = 6, freq = "D")

print(fechas)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')


In [5]:
s = pd.Series([1, 3, 5, np.nan, 6, 8], index = fechas, name = "datos")

print(s)

2013-01-01    1.0
2013-01-02    3.0
2013-01-03    5.0
2013-01-04    NaN
2013-01-05    6.0
2013-01-06    8.0
Freq: D, Name: datos, dtype: float64


In [6]:
# Un dataframe es un conjunto de columnas.

# creado a partir de arreglos de numpy.
df = pd.DataFrame( np.random.randn(6, 4), index = fechas,
    columns = ["A", "B", "C", "D"] )

print(df)

                   A         B         C         D
2013-01-01 -0.692425  0.291806 -0.939638  1.931861
2013-01-02 -1.179901  0.527429  0.366479 -1.035113
2013-01-03 -0.984117  0.322905 -0.190418 -0.191633
2013-01-04 -1.449449  1.180161 -1.666900 -1.194427
2013-01-05 -0.748434  0.956975  0.695292  1.016349
2013-01-06 -0.733160 -0.042479  0.172088  0.154935


In [7]:
# head() y tail() muestran la parte 
# superior e inferior del Dataframe.

print(df.head())
print()
print(df.tail())

                   A         B         C         D
2013-01-01 -0.692425  0.291806 -0.939638  1.931861
2013-01-02 -1.179901  0.527429  0.366479 -1.035113
2013-01-03 -0.984117  0.322905 -0.190418 -0.191633
2013-01-04 -1.449449  1.180161 -1.666900 -1.194427
2013-01-05 -0.748434  0.956975  0.695292  1.016349

                   A         B         C         D
2013-01-02 -1.179901  0.527429  0.366479 -1.035113
2013-01-03 -0.984117  0.322905 -0.190418 -0.191633
2013-01-04 -1.449449  1.180161 -1.666900 -1.194427
2013-01-05 -0.748434  0.956975  0.695292  1.016349
2013-01-06 -0.733160 -0.042479  0.172088  0.154935


In [8]:
# Podemos acceder al índice y las columnas.

print(df.index)
print()
print(df.columns)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

Index(['A', 'B', 'C', 'D'], dtype='object')


In [9]:
# Trasponer.

print(df.T)

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -0.692425   -1.179901   -0.984117   -1.449449   -0.748434   -0.733160
B    0.291806    0.527429    0.322905    1.180161    0.956975   -0.042479
C   -0.939638    0.366479   -0.190418   -1.666900    0.695292    0.172088
D    1.931861   -1.035113   -0.191633   -1.194427    1.016349    0.154935


In [10]:
# Convertir a un arreglo de numpy.

print( df.to_numpy() )

[[-0.69242532  0.29180555 -0.93963836  1.93186107]
 [-1.17990097  0.52742913  0.36647884 -1.03511333]
 [-0.98411722  0.32290481 -0.19041804 -0.19163282]
 [-1.44944856  1.18016105 -1.66689962 -1.19442743]
 [-0.74843375  0.95697513  0.6952923   1.01634935]
 [-0.73315983 -0.04247853  0.17208831  0.15493483]]


In [11]:
# Estadística descriptiva.

print( df.describe() )

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.964581  0.539466 -0.260516  0.113662
std    0.302055  0.454278  0.887454  1.203859
min   -1.449449 -0.042479 -1.666900 -1.194427
25%   -1.130955  0.299580 -0.752333 -0.824243
50%   -0.866275  0.425167 -0.009165 -0.018349
75%   -0.736978  0.849589  0.317881  0.800996
max   -0.692425  1.180161  0.695292  1.931861


In [12]:
# Ordenar datos.

# Por índice.

print( df.sort_index(ascending = False) )

                   A         B         C         D
2013-01-06 -0.733160 -0.042479  0.172088  0.154935
2013-01-05 -0.748434  0.956975  0.695292  1.016349
2013-01-04 -1.449449  1.180161 -1.666900 -1.194427
2013-01-03 -0.984117  0.322905 -0.190418 -0.191633
2013-01-02 -1.179901  0.527429  0.366479 -1.035113
2013-01-01 -0.692425  0.291806 -0.939638  1.931861


In [13]:
# Por columna.
print( df.sort_values(by = "B") )

                   A         B         C         D
2013-01-06 -0.733160 -0.042479  0.172088  0.154935
2013-01-01 -0.692425  0.291806 -0.939638  1.931861
2013-01-03 -0.984117  0.322905 -0.190418 -0.191633
2013-01-02 -1.179901  0.527429  0.366479 -1.035113
2013-01-05 -0.748434  0.956975  0.695292  1.016349
2013-01-04 -1.449449  1.180161 -1.666900 -1.194427


In [14]:
# Escoger una columna.

print( df["A"] )

2013-01-01   -0.692425
2013-01-02   -1.179901
2013-01-03   -0.984117
2013-01-04   -1.449449
2013-01-05   -0.748434
2013-01-06   -0.733160
Freq: D, Name: A, dtype: float64


In [15]:
# Escoger una fila.

print(df.index[0])
print( df.loc[df.index[0]] )

2013-01-01 00:00:00
A   -0.692425
B    0.291806
C   -0.939638
D    1.931861
Name: 2013-01-01 00:00:00, dtype: float64


In [16]:
# Escoger por número de fila.

print( df.iloc[0] )

A   -0.692425
B    0.291806
C   -0.939638
D    1.931861
Name: 2013-01-01 00:00:00, dtype: float64


In [17]:
# Escoger por fila y columna.

print( df.loc[df.index[2], "B"] )

0.3229048144608326


In [18]:
# Escoger por número de fila y columna.

print( df.iloc[2, 1] )

0.3229048144608326


In [19]:
# Escoger una subsección del dataframe.

df_2 = df.iloc[2:4, 1:3]
print( df_2 )

                   B         C
2013-01-03  0.322905 -0.190418
2013-01-04  1.180161 -1.666900


In [20]:
df_2 = df.iloc[2:4, :]
print( df_2 )

# Las copias y vistas funcionan igual que en numpy!!

                   A         B         C         D
2013-01-03 -0.984117  0.322905 -0.190418 -0.191633
2013-01-04 -1.449449  1.180161 -1.666900 -1.194427


In [21]:
# Búsqueda por condiciones.

# En una columna.
print( df[df["A"] > 0] )

Empty DataFrame
Columns: [A, B, C, D]
Index: []


In [22]:
# En todo el dataframe.

print( df[df>0] )

             A         B         C         D
2013-01-01 NaN  0.291806       NaN  1.931861
2013-01-02 NaN  0.527429  0.366479       NaN
2013-01-03 NaN  0.322905       NaN       NaN
2013-01-04 NaN  1.180161       NaN       NaN
2013-01-05 NaN  0.956975  0.695292  1.016349
2013-01-06 NaN       NaN  0.172088  0.154935


In [23]:
# Agregar columnas.
# Todos los elementos de una columna son del mismo tipo.
# Las columnas pueden tener distintos tipos.

df["E"] = ["uno", "uno", "dos", "tres", "cuatro", "tres"]

print(df)

                   A         B         C         D       E
2013-01-01 -0.692425  0.291806 -0.939638  1.931861     uno
2013-01-02 -1.179901  0.527429  0.366479 -1.035113     uno
2013-01-03 -0.984117  0.322905 -0.190418 -0.191633     dos
2013-01-04 -1.449449  1.180161 -1.666900 -1.194427    tres
2013-01-05 -0.748434  0.956975  0.695292  1.016349  cuatro
2013-01-06 -0.733160 -0.042479  0.172088  0.154935    tres


In [24]:
# Nueva columna con arreglos.

df["F"] = np.linspace(1, 5, 6)
print(df.head())

                   A         B         C         D       E    F
2013-01-01 -0.692425  0.291806 -0.939638  1.931861     uno  1.0
2013-01-02 -1.179901  0.527429  0.366479 -1.035113     uno  1.8
2013-01-03 -0.984117  0.322905 -0.190418 -0.191633     dos  2.6
2013-01-04 -1.449449  1.180161 -1.666900 -1.194427    tres  3.4
2013-01-05 -0.748434  0.956975  0.695292  1.016349  cuatro  4.2


In [25]:
# Buscar valores específicos con isin()

print( df[ df["E"].isin( ["dos", "cuatro"] ) ] )

                   A         B         C         D       E    F
2013-01-03 -0.984117  0.322905 -0.190418 -0.191633     dos  2.6
2013-01-05 -0.748434  0.956975  0.695292  1.016349  cuatro  4.2


In [26]:
df[ df["F"].isin( [1, 5] ) ]

A         B         C         D     E    F
2013-01-01 -0.692425  0.291806 -0.939638  1.931861   uno  1.0
2013-01-06 -0.733160 -0.042479  0.172088  0.154935  tres  5.0

In [27]:
# Podemos cambiar un valor específico.

df.iloc[0, 1] = 10
print(df)

                   A          B         C         D       E    F
2013-01-01 -0.692425  10.000000 -0.939638  1.931861     uno  1.0
2013-01-02 -1.179901   0.527429  0.366479 -1.035113     uno  1.8
2013-01-03 -0.984117   0.322905 -0.190418 -0.191633     dos  2.6
2013-01-04 -1.449449   1.180161 -1.666900 -1.194427    tres  3.4
2013-01-05 -0.748434   0.956975  0.695292  1.016349  cuatro  4.2
2013-01-06 -0.733160  -0.042479  0.172088  0.154935    tres  5.0


In [28]:
# Quitar columna.

df = df.drop("E", axis = 1)
print(df)

                   A          B         C         D    F
2013-01-01 -0.692425  10.000000 -0.939638  1.931861  1.0
2013-01-02 -1.179901   0.527429  0.366479 -1.035113  1.8
2013-01-03 -0.984117   0.322905 -0.190418 -0.191633  2.6
2013-01-04 -1.449449   1.180161 -1.666900 -1.194427  3.4
2013-01-05 -0.748434   0.956975  0.695292  1.016349  4.2
2013-01-06 -0.733160  -0.042479  0.172088  0.154935  5.0


In [29]:
# Quitar filas
df = df.drop(df.index[3], axis = 0)

df

A          B         C         D    F
2013-01-01 -0.692425  10.000000 -0.939638  1.931861  1.0
2013-01-02 -1.179901   0.527429  0.366479 -1.035113  1.8
2013-01-03 -0.984117   0.322905 -0.190418 -0.191633  2.6
2013-01-05 -0.748434   0.956975  0.695292  1.016349  4.2
2013-01-06 -0.733160  -0.042479  0.172088  0.154935  5.0

In [30]:
# Establecer valores con condicional.

df[df<0] = 0
print(df)

              A          B         C         D    F
2013-01-01  0.0  10.000000  0.000000  1.931861  1.0
2013-01-02  0.0   0.527429  0.366479  0.000000  1.8
2013-01-03  0.0   0.322905  0.000000  0.000000  2.6
2013-01-05  0.0   0.956975  0.695292  1.016349  4.2
2013-01-06  0.0   0.000000  0.172088  0.154935  5.0


In [31]:
# Agregamos algunos valores nulos.

df[df>2] = np.nan
print(df)

              A         B         C         D    F
2013-01-01  0.0       NaN  0.000000  1.931861  1.0
2013-01-02  0.0  0.527429  0.366479  0.000000  1.8
2013-01-03  0.0  0.322905  0.000000  0.000000  NaN
2013-01-05  0.0  0.956975  0.695292  1.016349  NaN
2013-01-06  0.0  0.000000  0.172088  0.154935  NaN


In [32]:
# Quitar filas con valores nulos.
print(df.dropna())
print()

# Rellenar valores nulos.
print(df.fillna(-100))
print()

# Determinar valores nulos.
print(df.isna())

              A         B         C    D    F
2013-01-02  0.0  0.527429  0.366479  0.0  1.8

              A           B         C         D      F
2013-01-01  0.0 -100.000000  0.000000  1.931861    1.0
2013-01-02  0.0    0.527429  0.366479  0.000000    1.8
2013-01-03  0.0    0.322905  0.000000  0.000000 -100.0
2013-01-05  0.0    0.956975  0.695292  1.016349 -100.0
2013-01-06  0.0    0.000000  0.172088  0.154935 -100.0

                A      B      C      D      F
2013-01-01  False   True  False  False  False
2013-01-02  False  False  False  False  False
2013-01-03  False  False  False  False   True
2013-01-05  False  False  False  False   True
2013-01-06  False  False  False  False   True


In [33]:
# operaciones.

# Entre columnas.
df["G"] = df["A"] + df["C"]

print(df)
print()

# promedio
print(df.mean())
print()
print(df.mean(1))

              A         B         C         D    F         G
2013-01-01  0.0       NaN  0.000000  1.931861  1.0  0.000000
2013-01-02  0.0  0.527429  0.366479  0.000000  1.8  0.366479
2013-01-03  0.0  0.322905  0.000000  0.000000  NaN  0.000000
2013-01-05  0.0  0.956975  0.695292  1.016349  NaN  0.695292
2013-01-06  0.0  0.000000  0.172088  0.154935  NaN  0.172088

A    0.000000
B    0.451827
C    0.246772
D    0.620629
F    1.400000
G    0.246772
dtype: float64

2013-01-01    0.586372
2013-01-02    0.510064
2013-01-03    0.064581
2013-01-05    0.672782
2013-01-06    0.099822
dtype: float64


In [34]:
# Aplicar operación.
# np.cumsum() hace una suma acumulada.
df.apply(np.cumsum)

A         B         C         D    F         G
2013-01-01  0.0       NaN  0.000000  1.931861  1.0  0.000000
2013-01-02  0.0  0.527429  0.366479  1.931861  2.8  0.366479
2013-01-03  0.0  0.850334  0.366479  1.931861  NaN  0.366479
2013-01-05  0.0  1.807309  1.061771  2.948210  NaN  1.061771
2013-01-06  0.0  1.807309  1.233859  3.103145  NaN  1.233859

In [35]:
# Logaritmo a cada elemento.
df["H"] = np.log( df["C"] )

df

/opt/homebrew/Caskroom/miniforge/base/envs/gv/lib/python3.9/site-packages/pandas/core/arraylike.py:364: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


A         B         C         D    F         G         H
2013-01-01  0.0       NaN  0.000000  1.931861  1.0  0.000000      -inf
2013-01-02  0.0  0.527429  0.366479  0.000000  1.8  0.366479 -1.003814
2013-01-03  0.0  0.322905  0.000000  0.000000  NaN  0.000000      -inf
2013-01-05  0.0  0.956975  0.695292  1.016349  NaN  0.695292 -0.363423
2013-01-06  0.0  0.000000  0.172088  0.154935  NaN  0.172088 -1.759748

In [36]:
# Recorrer una columna una cierta cantidad de filas.

df["I"] = df["C"].shift(2)

df

A         B         C         D    F         G         H  \
2013-01-01  0.0       NaN  0.000000  1.931861  1.0  0.000000      -inf   
2013-01-02  0.0  0.527429  0.366479  0.000000  1.8  0.366479 -1.003814   
2013-01-03  0.0  0.322905  0.000000  0.000000  NaN  0.000000      -inf   
2013-01-05  0.0  0.956975  0.695292  1.016349  NaN  0.695292 -0.363423   
2013-01-06  0.0  0.000000  0.172088  0.154935  NaN  0.172088 -1.759748   

                   I  
2013-01-01       NaN  
2013-01-02       NaN  
2013-01-03  0.000000  
2013-01-05  0.366479  
2013-01-06  0.000000

In [37]:
# Leer y escribir archivos es muy fácil con el formato
# csv, compatible con Excel.

# Escribir.
df.to_csv("Archivo1.csv")

In [38]:
# Leer archivo.

df_2 = pd.read_csv("Archivo1.csv", index_col = 0)
df_2

A         B         C         D    F         G         H  \
2013-01-01  0.0       NaN  0.000000  1.931861  1.0  0.000000      -inf   
2013-01-02  0.0  0.527429  0.366479  0.000000  1.8  0.366479 -1.003814   
2013-01-03  0.0  0.322905  0.000000  0.000000  NaN  0.000000      -inf   
2013-01-05  0.0  0.956975  0.695292  1.016349  NaN  0.695292 -0.363423   
2013-01-06  0.0  0.000000  0.172088  0.154935  NaN  0.172088 -1.759748   

                   I  
2013-01-01       NaN  
2013-01-02       NaN  
2013-01-03  0.000000  
2013-01-05  0.366479  
2013-01-06  0.000000

In [39]:
# El índice de fechas no se carga con el formato correcto.
print( df.index )
print( df_2.index )

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-05',
               '2013-01-06'],
              dtype='datetime64[ns]', freq=None)
Index(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-05', '2013-01-06'], dtype='object')


In [40]:
# Cambiamos al formato correcto.
df_2.index = pd.to_datetime( df_2.index )
df_2.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-05',
               '2013-01-06'],
              dtype='datetime64[ns]', freq=None)

In [41]:
# Correlación.

# Creamos un dataframe aleatorio.
df = pd.DataFrame( np.random.rand(100000, 2), columns = ["Col_1", "Col_2"] )

print( df.head() )
print()

# Matriz de correlación
print( df.corr() )
print()

# Matriz de covarianca
print( df.cov() )
print()

# Autocorrelación.
print( df["Col_1"].autocorr(lag = 1) )

      Col_1     Col_2
0  0.296689  0.081364
1  0.667543  0.639023
2  0.133929  0.738683
3  0.432362  0.245172
4  0.656807  0.457301

          Col_1     Col_2
Col_1  1.000000 -0.004124
Col_2 -0.004124  1.000000

          Col_1     Col_2
Col_1  0.083216 -0.000343
Col_2 -0.000343  0.083238

-0.0034425222432545198


In [42]:
# Cargar el archivo Electrico_residencial_2010_2017
# Selecciona las entradas correspondientes a Baja California.
# Ordena los datos de menor a mayor consumo en 2010.
# Selecciona los municipios con una cantidad de usuarios en 2012 menor a 100
# Encuentra el municipio con mayor consumo en tarifa DAC.
# Selecciona solo la tarifa DAC para todos los municipios.
# Encuentra la correlación entre el consumo de 2012 y 2013.

In [43]:
# Agrupar datos

fechas = pd.date_range("20130101", periods = 200, freq = "D")
df = pd.DataFrame( np.random.randn(200, 4), index = fechas,
    columns = ["A", "B", "C", "D"] )

print(df)

                   A         B         C         D
2013-01-01 -1.438076 -0.601575 -0.450797  0.762025
2013-01-02 -0.101053 -0.917234  0.410505 -0.688452
2013-01-03  0.686585 -0.954534 -0.476515  1.696198
2013-01-04  1.732757  0.102110  0.673183  0.894403
2013-01-05  0.287221 -0.792914  1.101796  1.197078
...              ...       ...       ...       ...
2013-07-15 -0.989184  1.746952  0.012504 -0.534332
2013-07-16 -1.721557  1.348815  0.164203  0.035089
2013-07-17 -0.151259  1.228167  1.627226  0.048818
2013-07-18  0.033141 -0.451652  1.709694  1.350428
2013-07-19 -0.296599  0.742159 -0.487532  0.011527

[200 rows x 4 columns]


In [44]:
# Agrupamos y realizamos una operación.
df.groupby(df.index.month).sum()

A         B         C         D
1  0.967453 -7.667261  2.271338  6.989130
2 -3.289937  0.691427  5.435141 -7.914718
3 -0.254666 -0.979370  6.725152  3.207552
4  3.980718 -7.285414 -6.081857  1.770468
5 -2.227700  3.016209  3.784511  6.633229
6 -0.854139 -2.391615 -2.823653 -1.632769
7 -2.165594  0.982634  3.523837  6.169124

In [45]:
df.groupby(df.index.day).mean()

A         B         C         D
1  -0.689058 -0.141548 -0.323411  0.773337
2  -0.524481 -0.745674  0.643935  0.017175
3   0.269406  0.296774 -0.380379  0.200025
4  -0.387438 -0.082012  0.759791  0.079524
5   0.090019 -0.115923  0.572139  0.059757
6   0.135394 -0.510957 -0.422119  0.168378
7   0.773068 -0.352431  0.240454 -0.178043
8  -0.119851 -0.275955 -0.296910 -0.755115
9  -0.399255 -0.412794  0.148751  0.132147
10  0.606130  0.578656  0.289379  0.165783
11 -0.536797 -1.035411 -0.251354  0.252710
12  0.063758 -0.628110  0.325947  0.015392
13 -0.512858  0.430342  0.122311 -0.192025
14 -0.137276 -0.511413  0.720313  0.448759
15 -0.194458  0.124904  0.221376 -0.654228
16 -0.228784  0.054401 -0.998035 -0.407787
17 -0.165097  0.518037  0.381893 -0.353409
18 -0.143802  0.030758  0.036566 -0.303284
19  0.209742  0.377224  0.324749 -0.039826
20 -0.319574 -0.180056 -0.033729  0.358148
21  0.755223 -0.156308 -0.016206  0.358465
22  0.639002  0.053538 -0.312958  0.883463
23 -0.118541 -0.126886 -0.279735  0.439620
24  0.094703  0.070258  0.044372  0.276444
25  0.403803  0.337943  0.060254  0.095760
26 -0.826656 -0.000549 -0.381382  0.156517
27  0.312682  0.286763 -0.320272  0.280625
28 -0.162450 -0.304266  0.084978 -0.017153
29  0.036490  0.682489  0.481951  0.868281
30  0.507929 -0.481700  0.248938 -0.111012
31  0.668784  0.762650  0.433441 -0.520189

In [46]:
# Concatenar dataframes.

# Creamos un dataframe aleatorio.
df_1 = pd.DataFrame(np.random.randn(100,2), columns = ["Col_1", "Col_2"])
df_2 = pd.DataFrame(np.random.randn(100,2), columns = ["Col_1", "Col_2"])

print(df_1.head())
print()
print(df_2.head())
print()

# Concatenamos.
df = pd.concat([df_1, df_2], axis = 0, ignore_index = True)

# Reiniciamos el índice.
df = df.reset_index(drop = True)

print(df)

      Col_1     Col_2
0  0.346116  0.871710
1 -0.348600 -1.136638
2  0.722027  0.575099
3 -1.090957  1.190842
4  0.099001 -0.962180

      Col_1     Col_2
0  0.473232 -0.199885
1  2.156939 -0.533408
2 -0.107902 -2.315383
3 -1.660630 -1.115910
4 -0.762037  0.125856

        Col_1     Col_2
0    0.346116  0.871710
1   -0.348600 -1.136638
2    0.722027  0.575099
3   -1.090957  1.190842
4    0.099001 -0.962180
..        ...       ...
195 -0.613604  1.819984
196 -1.160317 -0.463583
197  0.417002 -0.557350
198 -0.468153 -1.145942
199 -0.533366  1.420247

[200 rows x 2 columns]


In [47]:
# Concatenar dataframes.

# Creamos un dataframe aleatorio.
df_1 = pd.DataFrame(np.random.randn(100,2), columns = ["Col_1", "Col_2"])
df_2 = pd.DataFrame(np.random.randn(100,2), columns = ["Col_3", "Col_4"])

print(df_1.head())
print()
print(df_2.head())
print()

# Concatenamos.
df = pd.concat([df_1, df_2], axis = 1)

print(df)

      Col_1     Col_2
0 -0.488254  1.843923
1 -1.491169 -0.125679
2 -0.608179 -1.549635
3  0.083725  0.674484
4  0.397495 -0.563910

      Col_3     Col_4
0 -0.276993 -0.329882
1 -1.436838  0.246728
2 -1.233688 -0.083130
3  0.063574 -2.044710
4 -0.500643  0.629550

       Col_1     Col_2     Col_3     Col_4
0  -0.488254  1.843923 -0.276993 -0.329882
1  -1.491169 -0.125679 -1.436838  0.246728
2  -0.608179 -1.549635 -1.233688 -0.083130
3   0.083725  0.674484  0.063574 -2.044710
4   0.397495 -0.563910 -0.500643  0.629550
..       ...       ...       ...       ...
95  0.064618  0.720847  0.290224 -0.887515
96  0.344654 -2.041280 -0.276150 -1.015886
97 -1.390758  0.609607  1.133998  0.137532
98 -0.051474 -0.598544 -0.099250 -0.945249
99  2.943336 -1.340950 -1.387872  1.124751

[100 rows x 4 columns]
